-- Persist premium gold generated by extraction so inventory history can display it.
ALTER TABLE IF EXISTS public.resource_extraction_logs
ADD COLUMN IF NOT EXISTS "goldGenerated" NUMERIC NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_resource_extraction_logs_player_resource_date
ON public.resource_extraction_logs ("playerId", "resourceType", "createdAt" DESC);
