-- =============================================================================
-- sql/indexes.sql — Missing SQLite Indexes
-- Generated by SQL Audit (2026-04-05)
-- All statements are idempotent (CREATE INDEX IF NOT EXISTS)
-- Apply by running: sqlite3 game.db < sql/indexes.sql
-- =============================================================================

-- NOTE: Primary keys and UNIQUE columns already have implicit indexes:
--   users(id), users(username), users(email), users(firebase_uid)
--   regions(id), regions(name)
--   factories(id)
--   articles(id)
--   wars(id)
--   action_logs(id)
--   perks(userId, perkId)          <- composite PK
--   cooldowns(userId, actionType)  <- composite PK
--   user_factory_cooldowns(userId, factoryId) <- composite PK
-- The indexes below cover the remaining hot query paths.

-- -----------------------------------------------------------------------------
-- TABLE: users
-- Hot query: SELECT username, influence, money FROM users ORDER BY influence DESC LIMIT 10
-- Used by: GET /api/leaderboard (every leaderboard page load)
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_users_influence_desc
  ON users(influence DESC);

-- -----------------------------------------------------------------------------
-- TABLE: perks
-- Hot query: SELECT perkId, level FROM perks WHERE userId = ?
-- Used by: authenticate middleware (EVERY authenticated request)
-- Without index: full table scan grows with total players × perks
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_perks_userId
  ON perks(userId);

-- -----------------------------------------------------------------------------
-- TABLE: user_factory_cooldowns
-- Hot query: SELECT factoryId, lastUsed FROM user_factory_cooldowns WHERE userId = ?
-- Used by: GET /api/factories (fetches all cooldowns for current user)
-- The composite PK (userId, factoryId) is ordered userId-first, so this
-- query IS covered by the PK index — listed here for documentation clarity.
-- CREATE INDEX IF NOT EXISTS idx_ufc_userId ON user_factory_cooldowns(userId);
-- VERDICT: PK covers it. No additional index needed.

-- -----------------------------------------------------------------------------
-- TABLE: articles
-- Hot query 1: SELECT * FROM articles ORDER BY createdAt DESC LIMIT 50
-- Used by: GET /api/articles (main feed — called frequently)
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_articles_createdAt_desc
  ON articles(createdAt DESC);

-- Hot query 2: SELECT COUNT(*) FROM articles WHERE authorId = ? AND createdAt > ?
-- Used by: POST /api/articles rate-limit check (every article creation attempt)
-- Composite index covers both the equality filter and the range filter
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_articles_authorId_createdAt
  ON articles(authorId, createdAt);

-- -----------------------------------------------------------------------------
-- TABLE: wars
-- Hot query 1: SELECT * FROM wars WHERE status = 'active' ORDER BY startedAt DESC
-- Hot query 2: SELECT * FROM wars WHERE status = 'ended' ORDER BY endsAt DESC LIMIT 20
-- Used by: GET /api/wars (war dashboard)
-- Composite indexes allow index-only scan on (status filter + sort key)
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_wars_status_startedAt
  ON wars(status, startedAt DESC);

CREATE INDEX IF NOT EXISTS idx_wars_status_endsAt
  ON wars(status, endsAt DESC);

-- -----------------------------------------------------------------------------
-- TABLE: regions
-- Hot query: SELECT r.*, u.username FROM regions r LEFT JOIN users u ON r.ownerId = u.id
-- Used by: GET /api/regions (map load — called on every page visit)
-- Index on ownerId speeds up the JOIN lookup against users(id)
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_regions_ownerId
  ON regions(ownerId);

-- -----------------------------------------------------------------------------
-- TABLE: action_logs
-- Currently no SELECT queries use action_logs in the codebase (dead table).
-- Index added proactively for when audit/history queries are added.
-- Hot query (anticipated): SELECT * FROM action_logs WHERE userId = ? ORDER BY timestamp DESC
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_action_logs_userId_timestamp
  ON action_logs(userId, timestamp DESC);

-- =============================================================================
-- VERIFY — run after applying to confirm indexes exist:
-- SELECT name, tbl_name FROM sqlite_master WHERE type='index' ORDER BY tbl_name;
-- =============================================================================
